package execenv

import (
	"bytes"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"regexp"
	"strings"

	"github.com/pelletier/go-toml/v2"
	"github.com/pelletier/go-toml/v2/unstable"
	"gopkg.in/yaml.v3"
)

// ---------------------------------------------------------------------------
// Provider preset native config
//
// A provider preset's `native_config` is the family-native half of "which
// supplier this runtime talks to": the config fragment a family reads from a
// file rather than from the environment. Codex reads config.toml, Hermes reads
// config.yaml under HERMES_HOME, Reasonix reads a project config.toml, and
// OpenClaw reads the wrapper the daemon points OPENCLAW_CONFIG_PATH at.
//
// Each fragment is merged into the file the daemon already writes per task —
// never into the user's own config. That is the same reason the whole feature is
// server-side: a task's env root is disposable, the user's ~/.codex is not, and
// writing there would also let concurrent tasks overwrite each other.
//
// Merge order inside those files is "what the daemon synthesized → preset
// fragment", matching the env half of the decision (agent configuration →
// preset override). A preset that names a key wins; anything it omits keeps the
// value the daemon or the runtime owner supplied.
//
// A fragment that cannot be merged is DROPPED with a warning rather than
// failing preparation. A preset is a configuration choice, not data: the run it
// would have reconfigured is still a valid run against whatever else it
// inherited, and refusing to prepare would take the runtime offline over a
// typo in a config fragment.
// ---------------------------------------------------------------------------

const (
	codexPresetBeginMarker = "# BEGIN multica-managed provider-preset (do not edit; regenerated by daemon)"
	codexPresetEndMarker   = "# END multica-managed provider-preset"
)

// codexPresetBlockRe matches the managed block including its trailing blank
// lines, so removing it never leaves a gap where it used to sit.
var codexPresetBlockRe = regexp.MustCompile(
	`(?ms)^` + regexp.QuoteMeta(codexPresetBeginMarker) +
		`.*?^` + regexp.QuoteMeta(codexPresetEndMarker) + `\n*`)

// mergeProviderPresetFragment overlays a preset fragment onto a config map.
// Nested maps merge key by key; every other value type is replaced outright —
// a fragment is a set of overrides, and half-merging an array or a scalar has
// no meaning any of these families define.
func mergeProviderPresetFragment(base, fragment map[string]any) {
	// base is nil whenever the config being merged into does not have the
	// section yet (a Reasonix owner with no [permissions] table, an OpenClaw
	// wrapper whose caller skipped a key). Writing to a nil map panics, so
	// there is nothing to merge and the fragment is simply not applied.
	if base == nil {
		return
	}
	for k, v := range fragment {
		if subFragment, ok := v.(map[string]any); ok {
			// The nil check is load-bearing: a map-typed nil (a config section
			// that simply does not exist yet) survives the type assertion with
			// ok == true, and recursing into it would silently discard the
			// whole fragment instead of installing it.
			if subBase, ok := base[k].(map[string]any); ok && subBase != nil {
				mergeProviderPresetFragment(subBase, subFragment)
				continue
			}
		}
		base[k] = v
	}
}

// applyCodexProviderPreset rewrites the managed provider-preset block at the top
// of the task-local config.toml, or removes it when there is no fragment.
//
// The block goes FIRST, before the user's own tables, because TOML forbids a
// bare key after the first table header — appending it after a `[table]` the
// user wrote would produce a file Codex refuses to parse. The daemon's managed
// shell_environment_policy is appended later by the daemon and is a table, so
// it stays last.
//
// A fragment that collides with a key the user's config already defines makes
// the merged file invalid TOML; that case restores the file without the block
// and warns, so a duplicate-key typo degrades to "preset not applied" instead
// of a task that cannot start.
func applyCodexProviderPreset(configPath string, fragment map[string]any, logger *slog.Logger) error {
	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read config.toml: %w", err)
	}
	stale := codexPresetBlockRe.ReplaceAll(data, nil)

	content := string(bytes.TrimRight(stale, " \t\r\n"))
	if len(fragment) > 0 {
		block, err := renderCodexProviderPresetBlock(fragment)
		if err != nil {
			if logger != nil {
				logger.Warn("execenv: provider preset fragment is not renderable as TOML; running without it",
					"config_path", configPath, "error", err)
			}
		} else {
			// Drop whatever the fragment is about to redefine. TOML forbids a
			// duplicate key, so a preset that sets `model` next to a config
			// that already sets `model` would produce a file Codex cannot
			// parse — and `model` is the single most likely key for a supplier
			// preset to set.
			withoutConflicts, err := stripProviderPresetConflicts([]byte(content), fragment)
			if err != nil {
				if logger != nil {
					logger.Warn("execenv: cannot reconcile the provider preset with this config.toml; running without it",
						"config_path", configPath, "error", err)
				}
				withoutConflicts = []byte(content)
				block = ""
			}
			if block != "" {
				base := string(bytes.TrimRight(withoutConflicts, " \t\r\n"))
				candidate := block
				if base != "" {
					candidate = block + "\n\n" + base
				}
				var check map[string]any
				if err := toml.Unmarshal([]byte(candidate), &check); err != nil {
					if logger != nil {
						logger.Warn("execenv: provider preset fragment does not merge into this config.toml; running without it",
							"config_path", configPath, "error", err)
					}
				} else {
					content = candidate
				}
			}
		}
	}

	// Compared trimmed: dropping a trailing newline is not a change worth a
	// write, and rewriting a file we just decided not to touch would churn
	// mtime (and, for codex, invalidate the per-task models-cache binding)
	// on every single task.
	if strings.TrimRight(content, " \t\r\n") == strings.TrimRight(string(data), " \t\r\n") {
		return nil
	}
	if err := os.WriteFile(configPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write config.toml: %w", err)
	}
	if logger != nil {
		logger.Debug("execenv: provider preset written into codex config",
			"config_path", configPath, "applied", len(fragment) > 0)
	}
	return nil
}

// stripProviderPresetConflicts removes every expression whose root key the
// preset fragment also defines, so prepending the fragment cannot create a
// duplicate. A table takes its whole body with it: deleting only the
// `[profiles]` header would promote the body's keys to the root, silently
// turning a profile-only setting into a global one.
//
// Comments and every unrelated expression are preserved byte-for-byte, the same
// contract stripUserShellEnvPolicy holds.
func stripProviderPresetConflicts(content []byte, fragment map[string]any) ([]byte, error) {
	if len(bytes.TrimSpace(content)) == 0 {
		return content, nil
	}
	// Validate with the stable decoder first so a malformed user config is
	// never partially rewritten into a different malformed config.
	var decoded map[string]any
	if err := toml.Unmarshal(content, &decoded); err != nil {
		return nil, fmt.Errorf("parse config.toml before provider preset update: %w", err)
	}

	var parser unstable.Parser
	parser.Reset(content)
	var currentTable []string
	droppingTable := false
	ranges := make([]tomlByteRange, 0, 8)
	for parser.NextExpression() {
		expr := parser.Expression()
		keys := tomlNodeKeys(expr)
		switch expr.Kind {
		case unstable.Table, unstable.ArrayTable:
			currentTable = keys
			droppingTable = len(keys) > 0 && fragmentDeclaresKey(fragment, keys[0])
			if !droppingTable {
				continue
			}
			r, err := tomlTableHeaderLineRange(content, expr)
			if err != nil {
				return nil, err
			}
			ranges = append(ranges, r)
		case unstable.KeyValue:
			if droppingTable {
				start := int(expr.Raw.Offset)
				ranges = append(ranges, tomlByteRange{start: start, end: start + int(expr.Raw.Length)})
				continue
			}
			fullKey := make([]string, 0, len(currentTable)+len(keys))
			fullKey = append(fullKey, currentTable...)
			fullKey = append(fullKey, keys...)
			if len(fullKey) == 0 || !fragmentDeclaresKey(fragment, fullKey[0]) {
				continue
			}
			start := int(expr.Raw.Offset)
			ranges = append(ranges, tomlByteRange{start: start, end: start + int(expr.Raw.Length)})
		}
	}
	if err := parser.Error(); err != nil {
		return nil, fmt.Errorf("parse config.toml provider preset expressions: %w", err)
	}
	return removeTOMLByteRanges(content, ranges)
}

func fragmentDeclaresKey(fragment map[string]any, key string) bool {
	_, ok := fragment[key]
	return ok
}

func renderCodexProviderPresetBlock(fragment map[string]any) (string, error) {
	body, err := toml.Marshal(fragment)
	if err != nil {
		return "", fmt.Errorf("encode provider preset: %w", err)
	}
	var b bytes.Buffer
	b.WriteString(codexPresetBeginMarker)
	b.WriteByte('\n')
	b.Write(bytes.TrimRight(body, "\n"))
	b.WriteByte('\n')
	b.WriteString(codexPresetEndMarker)
	b.WriteByte('\n')
	return b.String(), nil
}

// mergeYAMLFragment overlays a preset fragment onto a parsed YAML document at
// the top level. It round-trips the fragment through YAML so the values land as
// real nodes (with the tags the encoder would have written) rather than as Go
// values the yaml package would have to guess about.
func mergeYAMLFragment(doc *yaml.Node, fragment map[string]any) error {
	if len(fragment) == 0 {
		return nil
	}
	raw, err := yaml.Marshal(fragment)
	if err != nil {
		return fmt.Errorf("encode provider preset: %w", err)
	}
	var parsed yaml.Node
	if err := yaml.Unmarshal(raw, &parsed); err != nil {
		return fmt.Errorf("decode provider preset: %w", err)
	}
	source := yamlDocumentRoot(&parsed)
	if source == nil || source.Kind != yaml.MappingNode {
		return errors.New("provider preset fragment is not a YAML mapping")
	}
	target := yamlDocumentRoot(doc)
	if target == nil || target.Kind != yaml.MappingNode {
		return errors.New("hermes config has no mapping root to merge into")
	}
	for i := 0; i+1 < len(source.Content); i += 2 {
		yamlSetMapValue(target, source.Content[i].Value, source.Content[i+1])
	}
	return nil
}
